version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1
  aws-sam: circleci/aws-sam-serverless@3.2.0

parameters:
  run-build_test_deploy-sam-dotnet6-app:
    type: boolean
    default: false

jobs:
  build_test_deploy-sam-dotnet6-app:
    machine:
      image: ubuntu-2004:2022.04.1
      docker_layer_caching: true
    resource_class: arm.medium
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: AWS SAM installation
          command: |
            sudo apt update
            sudo apt install python-is-python3 
            pip install aws-sam-cli
      - aws-sam/build:
          template:  sam-dotnet6-app/template.yaml
      - run:
          name: Test HelloWorldFunction
          command: |
            cd sam-dotnet6-app/HelloWorldFunction
            dotnet test test/HelloWorld.Test
      - aws-sam/deploy:
          stack-name: sam-dotnet6-app
          image-repositories: $AWS_ECR_HOST/mshk-sam-dotnet6-app

workflows:
  sam-java-app-workflow:
    when: << pipeline.parameters.run-build_test_deploy-sam-dotnet6-app >>
    jobs:
      - build_test_deploy-sam-dotnet6-app
